### ISSUE TITLE
Test against WordPress 6.0

### ISSUE THREAD

**Issue by vikrampm1** [10up/simple-local-avatars#108]
Is your enhancement related to a problem? Please describe.
Once WordPress 6.0 is released, we'll want to test Simple Local Avatars to see if any incompatibility issues arise.

Describe the solution you'd like

- [ ] test Simple Local Avatars on WordPress 6.0
- [ ] open issues for any incompatibilities noted in testing
- [ ] resolve issues identified in testing
- [ ] bump "tested up to" version
- [ ] if code changes needed due to incompatibilities, ship a plugin release, otherwise use "Plugin asset/readme update" action to update "tested up to" version on .org repo

Designs
n/a

Describe alternatives you've considered
none

Additional context
Related: #66, #56, #42, #35

**Comment by ajmaurya99** [comment]
I have tested this plugin in WordPress 6.0 version and it is working fine.

WP version : 6.0
Plugin version : 2.2.0
CC:  @jeffpaul @faisal-alvi
