### ISSUE TITLE
Incorecct Location of admin.js

### ISSUE THREAD

**Issue by thefrosty** [10up/simple-local-avatars#116]
### Describe the bug

Looking at the GitHub source, `/assets/js/admin.js` exists, but in the trunk of wp.org: https://plugins.svn.wordpress.org/simple-local-avatars/trunk/

See https://github.com/10up/simple-local-avatars/blob/develop/includes/class-simple-local-avatars.php#L1189

So getting a 404 on all admin pages. Also, shouldn't this only be loaded on the settings page too?

**Looks like a distignore issue**: https://github.com/10up/simple-local-avatars/blob/develop/.distignore#L5

### Steps to Reproduce

1. Visit admin, installed from dot org.
2. Note admin 404 requests to asset file.
3. Or visit code and see missing /assets directory.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
Possibly related to https://wordpress.org/support/topic/404-error-in-wordpress-admin/#post-15613085
