### ISSUE TITLE
HTTP_REFERER is null and causing php warning 

### ISSUE THREAD

**Issue by alireza-salehi** [10up/simple-local-avatars#123]
### Describe the bug

PHP Warning:  Undefined array key "HTTP_REFERER" in wp-content/plugins/simple-local-avatars/includes/class-simple-local-avatars.php on line 83

Version 2.3.0

### Steps to Reproduce

$_SERVER['HTTP_REFERER'] is not set and cause php warning getting WordPress log full of such warnings:
PHP Warning:  Undefined array key "HTTP_REFERER" in wp-content/plugins/simple-local-avatars/includes/class-simple-local-avatars.php on line 83

### WordPress information

version: 5.9.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by faisal-alvi** [comment]
Related: https://wordpress.org/support/topic/undefined-array-key-http_referer/
