### ISSUE TITLE
Add: Crop area options: Square, Freeform

### ISSUE THREAD

**Issue by faisal-alvi** [10up/simple-local-avatars#131]
### Is your enhancement related to a problem? Please describe.

* The crop feature was introduced in #83 with forced Square shape selection.
* Later, a "Skip crop" button and "Freeform" shape are added in #130 but now the Square shape selection is removed.
* So it is discussed from https://github.com/10up/simple-local-avatars/pull/130#issuecomment-1132219294 that we should allow users to crop in a "Square" shape or a "Freeform".

### Designs

Design discussion for the following area will be required, (i.e. **a:** where should we put buttons and **b:** how buttons should look like):

<img width="1274" alt="image" src="https://user-images.githubusercontent.com/25176325/170189260-7a2d65b6-b25c-4e8e-b49f-006adc7943af.png">

Go to "Users > Profile" (your edit profile section), and click the "Select avatar and crop" button to see the above screen.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
Initial thought is left aligned buttons for `Square Crop` (default) and `Freeform Crop`, though maybe they're not buttons so much as a left/right toggle for square vs. freeform crop since it will be one-or-the-other?

**Comment by faisal-alvi** [comment]
@dinhtungdu as discussed in the meeting, your point is that allowing a "freeform" crop does not make sense/worth because the end result of the avatar being loaded at FE is also cropped by the [WordPress](https://developer.wordpress.org/reference/functions/get_avatar/). So should we stick to the "strict square" selection?

Even setting the avatar with the "freeform" selection:

![image](https://user-images.githubusercontent.com/25176325/171826638-a19564ed-e960-4f22-83b9-e4635739e9e5.png)

At FE, the avatar loads cropped:

![image](https://user-images.githubusercontent.com/25176325/171826807-88df5654-d40a-4461-9dab-d699307be94f.png)

Please correct me if this was not the exact point.

**Comment by dinhtungdu** [comment]
@faisal-alvi you said it correctly! Freeform cropping creates more confusion than it solves IMO. If the final avatar displayed on the front end is still a square one. Even if we can hack it by storing the free-form cropped version in the user metadata, we still have a problem with the output HTML of the `get_avatar()` function, which set both `width` and `height` to the same value for the `<img>` tag.

**Comment by faisal-alvi** [comment]
@dkotter any thoughts on Tung's ^comment?

**Comment by dinhtungdu** [comment]
We can also try extending the functionality of the `get_avatar` function (maybe through filters). But I'm wondering how free-form avatars works with themes and other plugins, where a square avatar is generally expected.

**Comment by dkotter** [comment]
So `get_avatar` does allow you to have different sizes for height and width (through the `$args` attribute) but most common use cases are probably just squares. My suggestion would be to remove the freeform crop ability and we can always consider that in the future if we get more user requests. I think the `Skip cropping` feature solves the main issue we had

**Comment by dinhtungdu** [comment]
> So get_avatar does allow you to have different sizes for height and width (through the $args attribute)

I missed the `$args` parameter. Thanks for pointing this out!

Looking at the source, we can pass the width and height in pixel through the `$args` parameter, but for non-cropping avatars, we don't know the ratio, so width and height may not help here. Because we filter the avatar data, I'm thinking about checking if an avatar is free-form cropped and then setting the height to `auto` for them to preserve the ratio.

**Comment by dinhtungdu** [comment]
After testing against the current WordPress version and block themes, here are some additional observations:
- The cropped avatar is saved as the `full` size in the user metadata.
- Simple Local Avatars doesn't support retrieving the full-size avatar, though we can use `get_user_meta()` to get the avatar data.
- Comment Query Loop block only supports square avatar.

> My suggestion would be to remove the freeform crop ability and we can always consider that in the future if we get more user requests. I think the Skip cropping feature solves the main issue we had

I agree with this direction. We save the full avatar in the user metadata so it can be retrieved. But we should let users choose the cropping area for the square avatar.

**Comment by faisal-alvi** [comment]
Closing after #135

**Comment by faisal-alvi** [comment]
By the way, thanks for going in-depth and posting your research, great efforts @dinhtungdu
