### ISSUE TITLE
'assign_new_user_avatar' exception when passing url as $url_or_media_id with php 8

### ISSUE THREAD

**Issue by lllopo** [10up/simple-local-avatars#179]
### Describe the bug

When the `assign_new_user_avatar` function is called with first parameter (`$url_or_media_id`) being an url string and not a numeric media id, the function throws and exception on line 959 when running under PHP 8 :

```
Uncaught TypeError: Unsupported operand types: string + int in /SomePath/simple-local-avatars/includes/class-simple-local-avatars.php:959
Stack trace:
#0 /SomePath/SimpleLocalAvatarPlugin.php(56): Simple_Local_Avatars->assign_new_user_avatar('...', 56)
...
```

### Steps to Reproduce

1. Call programmatically the `assign_new_user_avatar` like this :

```
global $simple_local_avatars;

if ( isset( $simple_local_avatars ) ) {
	$current_user = wp_get_current_user();
	$simple_local_avatars->assign_new_user_avatar( 'some_url_string', $current_user->ID );
}
```

### WordPress information

Wordpress 6.1.1
PHP 8.0.15
SimpleLocalAvatars  2.7.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by faisal-alvi** [comment]
Note: This is coming from the fix #71
