### ISSUE TITLE
Add to Packagist

### ISSUE THREAD

**Issue by Log1x** [10up/simple-local-avatars#18]
Can we get this added to Packagist real quick? Looks like it never was and I'd prefer to bring it in via Composer.

Thanks!

**Comment by danielbachhuber** [comment]
Because the plugin is on WordPress.org, you can use Composer with WordPress Packagist: https://wpackagist.org/search?q=simple-local-avatars&type=any&search=

**Comment by jeffpaul** [comment]
@Log1x please see the suggestion above, which should resolve your issue.  Let us know if there's any further questions you have.

@danielbachhuber thanks for the assist on this!

**Comment by rmccue** [comment]
We're looking at bundling this with Altis, but we don't use third-party Composer repositories. Is it possible to get this published to the official Packagist repository @jeffpaul? ([Many other 10up repos are already](https://packagist.org/packages/10up/).)

**Comment by jeffpaul** [comment]
@rmccue seems reasonable, will look to get that set up and confirm when it's published there

**Comment by rmccue** [comment]
Thanks a bunch @jeffpaul (and thanks for the plugin)!

**Comment by jeffpaul** [comment]
@rmccue this is now up at https://packagist.org/packages/10up/simple-local-avatars, thanks to @tlovett1 for the assist on this!
