### ISSUE TITLE
PHP error due to trailing commas

### ISSUE THREAD

**Issue by dkotter** [10up/simple-local-avatars#195]
### Describe the bug

As reported on [WordPress.org](https://wordpress.org/support/topic/php-error-after-update-15/), there's a PHP error linked to [these lines](https://github.com/10up/simple-local-avatars/blob/develop/includes/class-simple-local-avatars.php#L527-L533).

It was hypothesized that this was due to the missing textdomain, though I didn't think that would cause a problem. After further user testing, it seems to be an issue with a trailing comma in those translation functions. In doing some research, this seemed to be something that would cause an issue in PHP 7.2 or less but was [fixed in PHP 7.3+](https://php.watch/versions/7.3/func-call-trailing-comma). Our PHP minimum is 7.4 so I didn't think this would be an issue but the user report we got is using PHP 8.1, so seems like maybe this doesn't fully work in PHP 7.3+?

I don't think there's any need to have those commas so a quick fix here is to remove those. 

### Steps to Reproduce

I've not reproduced myself but see the [WordPress.org thread](https://wordpress.org/support/topic/php-error-after-update-15/) for more details.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sekra24** [comment]
Hey @dkotter , just submitted a pull request. Hope that helps ;)
