### ISSUE TITLE
Move 'simple_local_avatar_deleted' action in 'avatar_delete'

### ISSUE THREAD

**Issue by lllopo** [10up/simple-local-avatars#199]
### Is your enhancement related to a problem? Please describe.

Currently the 'simple_local_avatar_deleted' is placed in 'action_remove_simple_local_avatar' which happens on http requests. This means that if someone does 'avatar_delete' programmatically (which I'm doing in a plugin I'm writing) this action won't trigger which is not good and the programmer will have to call this action explicitly in addition to 'avatar_delete'.

### Describe alternatives you've considered

Moving 'simple_local_avatar_deleted' in the 'avatar_delete' method would solve this without additional implications, I think.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
@faisal-alvi any thoughts on this?

**Comment by faisal-alvi** [comment]
Sure, making this change doesn't appear to have any implications. I'll proceed with creating a pull request.
