### ISSUE TITLE
get_avatar $args not being passed on

### ISSUE THREAD

**Issue by scheinercc** [10up/simple-local-avatars#206]
### Describe your question

Hi there,
For the following code the image shows, `120px` get set and so does `alt-test`. But the class in the `$args` array does not get added to the `class` list.

```
get_avatar( $author_id, '120', '', 'alt-test', [ 'class' => [ 'rounded-full' ] ] );
```
I tried
```
[ 'class' => [ 'rounded-full' ] ]
```
```
$args = [ 'class' => 'rounded-full' ]
```
```
$args = array( 'class' => 'rounded-full' )
```
```
$args = array( 'height' => '2000', 'class' => 'rounded-full' )
```

Checked https://developer.wordpress.org/reference/functions/get_avatar/#source, where in line 2862 it checks for `$args['class']`. Had a look at your source and as far as I could see the `$args` parameter is being passed on.
Any other ideas why that might be or how if could test where it vanishes?

Thanks!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dkotter** [comment]
@scheinercc Thanks for the question. I tested this out and it was working for me.

I tried:
```php
get_avatar( get_the_author_meta( 'ID' ), '120', '', 'This is alt text', [ 'class' => [ 'first', 'second' ] ] )
```

And:
```php
get_avatar( get_the_author_meta( 'ID' ), '120', '', 'This is alt text', [ 'class' => 'first' ] )
```

and both worked as expected. Note though that any classes you pass in get added in addition to any existing classes. So my final output had the classes `class="avatar avatar-120 first second"`

**Comment by scheinercc** [comment]
@dkotter thanks lots for taking the time and testing it from your end. Will have to see if I can find out what else might be modifying `get_avatar` in my system. In the unlikely case it has something to do with this plugin, I will let you know here.
