### ISSUE TITLE
Avatar randomnly removed

### ISSUE THREAD

**Issue by eflorea** [10up/simple-local-avatars#21]
Randomly the avatar disappears (the usermeta "simple_local_avatar" is being removed from database).

Tracking it down to https://github.com/10up/simple-local-avatars/blob/develop/simple-local-avatars.php#L97  might be the issue. There is logic in there when getting the avatar to auto-clean it if cannot be found if a WP user is logged in.
So what happens I believe is that get_attached_file fails (filesystem not available - maybe some use of S3, Azure storage plugins) so the avatar is removed.

So maybe a fix would be either remove the auto-clean, check filesystem is accessible before check file exists or add some sort of setting that enables/disables this.

**Comment by adamsilverstein** [comment]
This deletion code was added in https://github.com/10up/simple-local-avatars/commit/4d70c3bd9ceda6a7e09532202d1a9d373d8b3743#diff-8a365e46b40b96d3ced40af92233550eR96 without explaination. We should probably remove this as it can unintentionally delete meta if a file read fails for any reason.
