### ISSUE TITLE
PHP warnings due to wrong param type

### ISSUE THREAD

**Issue by dkotter** [10up/simple-local-avatars#224]
### Describe the bug

As reported on [WordPress.org](https://wordpress.org/support/topic/error-during-authorization-to-rocketchat/), seems there's some situations that can result in PHP warnings. I have not been able to reproduce myself but in looking at the code, I think we can add a couple checks here to easily suppress these warnings.

### Steps to Reproduce

See https://wordpress.org/support/topic/error-during-authorization-to-rocketchat/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vikrampm1** [comment]
Maybe we can close https://github.com/10up/simple-local-avatars/issues/220 in favor of this if they're related?

**Comment by dkotter** [comment]
> Maybe we can close #220 in favor of this if they're related?

No, these are different issues. #220 is about adding PHP version checks whereas this issue is about some users getting PHP warnings
