### ISSUE TITLE
The default avatar is displayed as a broken for all users when the custom image option is selected.

### ISSUE THREAD

**Issue by ankitguptaindia** [10up/simple-local-avatars#231]
### Describe the bug

**Default avatar is not rendering correctly for all users when custom default avatar setting is selected.. Instead of displaying the chosen custom image, a broken image icon is shown, indicating that the avatar cannot be loaded or displayed properly.**

| Default Avatar | Users List |
|--------|--------|
| ![Screenshot 2023-09-03 at 12 42 24 PM](https://github.com/10up/simple-local-avatars/assets/6384299/f7c89e6f-1568-484e-82b1-30afc1054796) | ![Screenshot 2023-09-03 at 12 42 39 PM](https://github.com/10up/simple-local-avatars/assets/6384299/68028a0f-9bd5-4fe0-a8c3-bffa420a710c) |

### When selecting other option for the Default Avatar

| Default Avatar | Users List |
|--------|--------|
| ![Screenshot 2023-09-03 at 12 45 25 PM](https://github.com/10up/simple-local-avatars/assets/6384299/6c00529d-6916-46f8-974d-e42babc7d8f3) | ![Screenshot 2023-09-03 at 12 45 37 PM](https://github.com/10up/simple-local-avatars/assets/6384299/e025570c-7b38-410f-829c-93a6f81efb75) | 

### Expected Result:

When an admin selects the option to use a custom image as their avatar, the chosen image should be displayed consistently across the system, replacing the default avatar.

**_Please note that this issue is also happening with WordPress 6.2 so not related to WP 6.3 update._**

https://github.com/10up/simple-local-avatars/assets/6384299/a6ad21bf-12ea-49cf-b7ae-6a20cb17e9c1

### Steps to Reproduce:

1. Access the avatar settings.
2. Choose the option to upload a custom image as your avatar.
3. Upload a custom image.
4. Save the changes.
5. View the user's profile or avatar in various parts of the system.

### Environment information

<Details>
`
### wp-core ###

version: 6.2
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 0
default_comment_status: open
environment_type: production
user_count: 41
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/vevecojuya2747/web/scary-swan-vowu.instawp.xyz/public_html
wordpress_size: 50.67 MB (53126948 bytes)
uploads_path: /home/vevecojuya2747/web/scary-swan-vowu.instawp.xyz/public_html/wp-content/uploads
uploads_size: 2.34 MB (2456707 bytes)
themes_path: /home/vevecojuya2747/web/scary-swan-vowu.instawp.xyz/public_html/wp-content/themes
themes_size: 7.50 MB (7867712 bytes)
plugins_path: /home/vevecojuya2747/web/scary-swan-vowu.instawp.xyz/public_html/wp-content/plugins
plugins_size: 53.94 MB (56558969 bytes)
database_size: 5.06 MB (5308416 bytes)
total_size: 119.51 MB (125318752 bytes)

### wp-active-theme ###

name: Storefront (storefront)
version: 4.5.2
author: Automattic
author_website: https://woocommerce.com/
parent_theme: none
theme_features: core-block-patterns, widgets-block-editor, automatic-feed-links, post-thumbnails, custom-logo, menus, html5, custom-background, custom-header, site-logo, title-tag, customize-selective-refresh-widgets, wp-block-styles, align-wide, editor-styles, editor-font-sizes, editor-style, responsive-embeds, amp, starter-content, widgets
theme_path: /home/vevecojuya2747/web/scary-swan-vowu.instawp.xyz/public_html/wp-content/themes/storefront

### wp-themes-inactive (1) ###

Twenty Twenty-Three: version: 1.2, author: the WordPress team

### wp-plugins-active (3) ###

FakerPress: version: 0.6.1, author: Gustavo Bordoni
Simple Local Avatars: version: 2.7.5, author: 10up
WP Downgrade | Specific Core Version: version: 1.2.6, author: Reisetiger

### wp-plugins-inactive (2) ###

Pig Latin: version: 0.2, author: Nikolay Bachiyski
WooCommerce: version: 8.0.3, author: Automattic

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1690
imagemagick_version: ImageMagick 6.9.10-23 Q16 x86_64 20190101 https://imagemagick.org
imagick_version: 3.7.0
file_uploads: File uploads is turned off
post_max_size: 64M
upload_max_filesize: 64M
max_effective_size: 64 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 122 MB
	imagick::RESOURCETYPE_DISK: 1073741824
	imagick::RESOURCETYPE_FILE: 768
	imagick::RESOURCETYPE_MAP: 512 MB
	imagick::RESOURCETYPE_MEMORY: 256 MB
	imagick::RESOURCETYPE_THREAD: 1
	imagick::RESOURCETYPE_TIME: 1.844674407371E+19
imagemagick_file_formats: 3FR, 3G2, 3GP, AAI, AI, ART, ARW, AVI, AVS, BGR, BGRA, BGRO, BIE, BMP, BMP2, BMP3, BRF, CAL, CALS, CANVAS, CAPTION, CIN, CIP, CLIP, CMYK, CMYKA, CR2, CRW, CUR, CUT, DATA, DCM, DCR, DCX, DDS, DFONT, DJVU, DNG, DOT, DPX, DXT1, DXT5, EPDF, EPI, EPS, EPS2, EPS3, EPSF, EPSI, EPT, EPT2, EPT3, ERF, EXR, FAX, FILE, FITS, FRACTAL, FTP, FTS, G3, G4, GIF, GIF87, GRADIENT, GRAY, GRAYA, GROUP4, GV, H, HALD, HDR, HISTOGRAM, HRZ, HTM, HTML, HTTP, HTTPS, ICB, ICO, ICON, IIQ, INFO, INLINE, IPL, ISOBRL, ISOBRL6, JBG, JBIG, JNG, JNX, JPE, JPEG, JPG, JPS, JSON, K25, KDC, LABEL, M2V, M4V, MAC, MAGICK, MAP, MASK, MAT, MATTE, MEF, MIFF, MKV, MNG, MONO, MOV, MP4, MPC, MPEG, MPG, MRW, MSL, MSVG, MTV, MVG, NEF, NRW, NULL, ORF, OTB, OTF, PAL, PALM, PAM, PANGO, PATTERN, PBM, PCD, PCDS, PCL, PCT, PCX, PDB, PDF, PDFA, PEF, PES, PFA, PFB, PFM, PGM, PGX, PICON, PICT, PIX, PJPEG, PLASMA, PNG, PNG00, PNG24, PNG32, PNG48, PNG64, PNG8, PNM, PPM, PREVIEW, PS, PS2, PS3, PSB, PSD, PTIF, PWP, RADIAL-GRADIENT, RAF, RAS, RAW, RGB, RGBA, RGBO, RGF, RLA, RLE, RMF, RW2, SCR, SCT, SFW, SGI, SHTML, SIX, SIXEL, SPARSE-COLOR, SR2, SRF, STEGANO, SUN, SVG, SVGZ, TEXT, TGA, THUMBNAIL, TIFF, TIFF64, TILE, TIM, TTC, TTF, TXT, UBRL, UBRL6, UIL, UYVY, VDA, VICAR, VID, VIFF, VIPS, VST, WBMP, WEBP, WMF, WMV, WMZ, WPG, X, X3F, XBM, XC, XCF, XPM, XPS, XV, XWD, YCbCr, YCbCrA, YUV
gd_version: 2.3.3
gd_formats: GIF, JPEG, PNG, WebP, BMP, XPM
ghostscript_version: unknown

### wp-server ###

server_architecture: Linux 5.4.0-153-generic x86_64
httpd_software: Apache/2.4.57 (Ubuntu) mod_fcgid/2.3.9 OpenSSL/1.1.1f
php_version: 7.4.33 64bit
php_sapi: fpm-fcgi
max_input_variables: 1000
time_limit: 30
memory_limit: 128M
admin_memory_limit: 256M
max_input_time: 60
upload_max_filesize: 64M
php_post_max_size: 64M
curl_version: 7.68.0 OpenSSL/1.1.1f
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 10.6.14-MariaDB-1:10.6.14+maria~ubu2004
client_version: mysqlnd 7.4.33
max_allowed_packet: 16777216
max_connections: 151

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/vevecojuya2747/web/scary-swan-vowu.instawp.xyz/public_html/wp-content
WP_PLUGIN_DIR: /home/vevecojuya2747/web/scary-swan-vowu.instawp.xyz/public_html/wp-content/plugins
WP_MEMORY_LIMIT: 40M
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: true
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: true
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

`
</Details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by faisal-alvi** [comment]
@ankitguptaindia thanks for the report. I have tried to regenerate the issue but the default avatar is working as expected for me. Please check the video below. Can you please check it in a different set? I'm happy to jump on a call to test together.

https://github.com/10up/simple-local-avatars/assets/25176325/d0ceb983-9b9f-4a65-946b-00fd484227a7

**Testing Environment -**

<details>

- **WordPress:** 6.3.1
- **Theme:** Twenty Twenty-Three: 1.2
- **WooCommerce** - 7.9.0
- **OS:** macOS 14.0 Beta (23A5337a)

</details>

**Comment by ankitguptaindia** [comment]
@faisal-alvi Thanks for checking this issue. I am still facing this issue on this disposable site. 
You can try this here: 
https://scary-swan-vowu.instawp.xyz/wp-admin
UN- kajomakewu2507
PW- xzA2S6TLwaV5d7HGMsFU

**Comment by faisal-alvi** [comment]
@ankitguptaindia I have a strong feeling that after #216 is reverted (i.e. #245), this issue should also be fixed. Can you please check again in the `develop` branch and let me know?

**Comment by ankitguptaindia** [comment]
>@ankitguptaindia I have a strong feeling that after https://github.com/10up/simple-local-avatars/pull/216 is reverted (i.e. https://github.com/10up/simple-local-avatars/issues/245), this issue should also be fixed. Can you please check again in the develop branch and let me know?

Hi @faisal-alvi I checked this again with the `develop` branch and unfortunately, I still face this issue. 

https://github.com/10up/simple-local-avatars/assets/6384299/a1c0f7e5-6d31-47e0-b532-2551c1554261
