### ISSUE TITLE
Critical issue in version 2.7.6 when used with S3 Uploads plugin

### ISSUE THREAD

**Issue by leogermani** [10up/simple-local-avatars#245]
### Describe the bug

We are having a severe issue with the latest released version (2.7.6) when used along a cloud storage plugin (in our case, we use S3-Uploads plugin). The result is the site becomes unresponsive.

The issue seems to have been introduced in [#216](https://github.com/10up/simple-local-avatars/pull/216).

From a quick look, the issues seems to be that the external S3 URL is returned [here](https://github.com/10up/simple-local-avatars/pull/216/files#diff-a05d559d485d184224ad87c7e310a12068ce060290bcdda4e1001d3d4e6bea89R390), and thus the replacement done [here](https://github.com/10up/simple-local-avatars/pull/216/files#diff-a05d559d485d184224ad87c7e310a12068ce060290bcdda4e1001d3d4e6bea89R403) will never work.

This apparently causes the site to keep creating new image sizes forever.

This is a guess about the cause, not confirmed.

It would be awesome if you could have a look at this, because we are unable to update the plugin in many of our sites.

Thanks!

### Steps to Reproduce

* Set up a site with Simple Local Avatars and S3 Uploads plugin. 
* Browse the site and watch the traffic and response time increase
* Watch the log for Warnings in the S3 integrations like `PHP Warning:  Error executing "PutObject" on "https://bdn-data.s3.amazonaws.com/uploads/2020/06/1200px-Associated_Press_logo_2012.svg_-1-96x96.png"; AWS HTTP error: Server error: `PUT https://bdn-data.s3.amazonaws.com/uploads/2020/06/1200px-Associated_Press_logo_2012.svg_-1-96x96.png` resulted in a `503 Slow Down``

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by faisal-alvi** [comment]
@leogermani fix #247 (reverting #216) is merged into the `develop` branch, can you please confirm the issue you mentioned is fixed?

**Comment by leogermani** [comment]
Hi @faisal-alvi , I'm sorry I didn't reply in time, but wanted to thank you for the fix. I confirm our sites are working fine again with the latest version.

Thank you!
