### ISSUE TITLE
2.7.6 Introduces Breaking Changes For Avatars Outside the Media Library

### ISSUE THREAD

**Issue by jakejackson1** [10up/simple-local-avatars#246]
### Describe the bug

The changes introduced in https://github.com/10up/simple-local-avatars/pull/216 cause multiple breaking-changes for avatars not stored in the media library (no `media_id`).

If the avatar has been previously set with `Simple_Local_Avatars::assign_new_user_avatar( $url, $user_id )` – or via a third party – and is not stored in the media library, the following breaking changes occur:

1. The rating system is bypassed when the requested size exists. This allows for X/R-rated avatars to be displayed on a G-rated site
2. If a requested image size does not exist, and the image is stored in the uploads directory, it will no longer be dynamically generated
3. If a requested image size does not exist, and the image is not stored in the uploads directory/or dynamic resizing is turned off or fails, the full-size image is not returned

I was originally going to submit a PR to fix item 3, which is the bug I first found. But the more I reviewed the changes, the more fundamental issues I found with the newly-introduced changes (also https://github.com/10up/simple-local-avatars/issues/245). I'd strongly consider rolling back #216 👍

### Steps to Reproduce

For bug 1

1. In v2.7.5 use `$simple_local_avatars->assign_new_user_avatar( $url, $user_id )` to assign an image stored in the `uploads` directory (but not the media library) 
2. Go to the associated user profile and set the rating to R
3. Go to Settings -> Discussions and ensure the site rating is set to G
4. Leave a comment on a post as the user. The avatar will show the fallback in the comment.
5. Upgrade to v2.7.6 and view the comment. The rated R avatar will be showing.

For bug 2

1. In v2.7.5 use `$simple_local_avatars->assign_new_user_avatar( $url, $user_id )` to assign an image stored in the `uploads` directory (but not the media library) 
2. View the user profile (lets call this User A) and see the fallback avatar
3. Leave a comment on a post as the user. A resized version of the avatar will show
4. Upgrade to 2.7.6 and repeat the above steps with a separate user (User B)
5. User A will have their avatar showing in the comments, while User B will have the fallback avatar

For bug 3

1. In v2.7.6 use `$simple_local_avatars->assign_new_user_avatar( $url, $user_id )` to assign an image stored in the `uploads` directory (but not the media library) 
2. View the user profile and see the fallback avatar

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by faisal-alvi** [comment]
@jakejackson1 fix #247 (reverting #216) is merged into the `develop` branch, can you please confirm the issues mentioned above are fixed?

**Comment by jakejackson1** [comment]
@faisal-alvi thanks. I can confirm all three issues are now fixed in the `develop` branch 👍
