### ISSUE TITLE
Bug: Different sizes for avatar

### ISSUE THREAD

**Issue by worldsdream** [10up/simple-local-avatars#251]
### Describe the bug

When you upload an image for a user, it creates 5 sizes for the avatar (and the original ofcourse). It should only upload the original and that's it.

Uploading a picture creates the below sizes:

- original size
- 50×50
- 96×96
- 100×100
- 192×192
- 200×200

Default theme, no plugins installed, except the plugin Simple Local Avatars.

Image sizes in media settings are all “0”.

This happens when you upload a picture for the user. This does not happen when you choose a default avatar. When choosing a default avatar, it only uploads the original size and that's it (which is good).

Let me know if you need more information so we can have this fixed!

### Steps to Reproduce

Go to a user and upload a picture. Check the upload folder, you will see different sizes.
Go to the settings and upload a default avatar. Check the upload folder, you will see only the original uploaded picture (this is good).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
Noting that this was originally reported here: https://wordpress.org/support/topic/why-so-many-different-sizes-of-the-avatar/#post-17288493

**Comment by jeffpaul** [comment]
@worldsdream those additional image sizes are created by WordPress by default and in most cases because of the theme you have active.  You can read a bit more about that here: https://kinsta.com/blog/wordpress-image-sizes/.
