### ISSUE TITLE
Local Avatar not displaying on my mobile, .author-bio-avatar -> display:none

### ISSUE THREAD

**Issue by dvjrickkraft** [10up/simple-local-avatars#258]
### Describe the bug

Hi, really love the plugin, just noticed it's not displaying the Avatar on mobile devices.  I can replicate it using Firefox / F12 to inspect and changing to mobile. Customizing a post with OceanWP it's not there, and dynamically resizing Firefox 122.0.1 (64-bit) it's actually there until almost the very narrowest when it disappears. My Xiaomi 11T has a 1080 x 2400 so it shouldn't be a viewport issue, but seems like it.  Is there a way to force it to show no matter what? Forcing an Android to report the correct pixel viewport seems unlikely?

I'm using an OceanWP Child theme, tried to edit this but not great at coding, and it was challenging for me to find this a second time let alone to snip the correct CSS entry, but I copy-pasted when I first found it: 
public_html/wp-content/themes/oceanwp/assets/css
in: style.min.css
...
6883  @media only screen and (max-width: 480px) {
6884    #author-bio .author-bio-avatar {
6885      display:none

I tried a little CSS editing and deleting/reuploading/clearing cache but I couldn't affect or get it to display at all.  Any suggestions or help would be greatly appreciated, and thanks for your time!

### Steps to Reproduce

1) Visit https://www.techspinreview.com/2023-cooler-master-haf-500/ on a mobile device
2) Scroll down to near bottom of page
3) My avatar isn't appearing 😣

### Screenshots, screen recording, code snippet

![Screenshot 2024-02-19 021622](https://github.com/10up/simple-local-avatars/assets/5501662/c0c86918-c619-4939-b175-7532c155ad00)

### Environment information

Xiaomi 11T MIUI Global 14.0.5 Android 13

### WordPress information

`
### wp-core ###

version: 6.4.3
site_language: en_US
user_language: en_US
timezone: +08:00
permalink: /%year%-%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: undefined
environment_type: production
user_count: 4
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/techspin/public_html
wordpress_size: 4.46 GB (4788820187 bytes)
uploads_path: /home/techspin/public_html/wp-content/uploads
uploads_size: 404.41 MB (424054376 bytes)
themes_path: /home/techspin/public_html/wp-content/themes
themes_size: 27.04 MB (28353392 bytes)
plugins_path: /home/techspin/public_html/wp-content/plugins
plugins_size: 316.09 MB (331443353 bytes)
database_size: 182.03 MB (190873600 bytes)
total_size: 5.37 GB (5763544908 bytes)

### wp-dropins (2) ###

advanced-cache.php: true
object-cache.php: true

### wp-active-theme ###

name: OceanWP Child (oceanwp-child)
version: 1.0
author: Nick
author_website: https://oceanwp.org/
parent_theme: OceanWP (oceanwp)
theme_features: core-block-patterns, widgets-block-editor, align-wide, wp-block-styles, responsive-embeds, editor-styles, editor-style, menus, post-formats, title-tag, automatic-feed-links, post-thumbnails, custom-header, custom-logo, html5, woocommerce, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, customize-selective-refresh-widgets, widgets
theme_path: /home/techspin/public_html/wp-content/themes/oceanwp-child
auto_update: Disabled

### wp-parent-theme ###

name: OceanWP (oceanwp)
version: 3.5.3
author: OceanWP
author_website: https://oceanwp.org/about-oceanwp/
theme_path: /home/techspin/public_html/wp-content/themes/oceanwp
auto_update: Disabled

### wp-themes-inactive (1) ###

Twenty Twenty-Four: version: 1.0, author: the WordPress team, Auto-updates disabled

### wp-mu-plugins (1) ###

WP Password bcrypt: version: 1.1.0, author: Roots

### wp-plugins-active (38) ###

ACF QuickEdit Fields: version: 3.3.0, author: Jörn Lund, Auto-updates enabled
AddToAny Share Buttons: version: 1.8.9, author: AddToAny, Auto-updates enabled
Advanced Custom Fields: version: 6.2.6.1, author: WP Engine, Auto-updates enabled
All-in-One WP Migration: version: 7.79, author: ServMask, Auto-updates enabled
CookieYes | GDPR Cookie Consent: version: 3.1.8, author: CookieYes, Auto-updates enabled
Custom 404 Pro: version: 3.10.1, author: Kunal Nagar, Auto-updates disabled
Custom Permalinks: version: 2.5.2, author: Sami Ahmed Siddiqui, Auto-updates enabled
Disable XML-RPC: version: 1.0.1, author: Philip Erb, Auto-updates enabled
Duplicate Page: version: 4.5.3, author: mndpsingh287, Auto-updates enabled
Elementor: version: 3.19.2, author: Elementor.com, Auto-updates enabled
Elementor Header & Footer Builder: version: 1.6.25, author: Brainstorm Force, Nikhil Chavan, Auto-updates enabled
Elementor Pro: version: 3.19.1, author: Elementor.com (latest version: 3.19.2), Auto-updates disabled
Essential Addons for Elementor: version: 5.9.9, author: WPDeveloper, Auto-updates enabled
Favicon by RealFaviconGenerator: version: 1.3.28, author: Philippe Bernard, Auto-updates enabled
Html5 Video Player: version: 2.5.27, author: bPlugins LLC, Auto-updates enabled
LoginPress: version: 3.0.5, author: LoginPress, Auto-updates enabled
Media Library Assistant: version: 3.13, author: David Lingren, Auto-updates enabled
myStickymenu: version: 2.6.7, author: Premio, Auto-updates enabled
Ocean Extra: version: 2.2.5, author: OceanWP, Auto-updates enabled
Opt-Out for Google Analytics (DSGVO / GDPR): version: 2.2, author: Schweizer Solutions GmbH, Auto-updates enabled
Rank Math SEO: version: 1.0.212.1, author: Rank Math, Auto-updates enabled
Redirection: version: 5.4.2, author: John Godley, Auto-updates enabled
Robin image optimizer: version: 1.6.7, author: Creative Motion <info@cm-wp.com>, Auto-updates enabled
Search Meter: version: 2.13.5, author: Bennett McElwee, Auto-updates enabled
Simple History: version: 4.10.0, author: Pär Thernström, Auto-updates enabled
Simple Lightbox: version: 2.9.3, author: Archetyped, Auto-updates enabled
Simple Local Avatars: version: 2.7.7, author: 10up, Auto-updates enabled
Site Kit by Google: version: 1.120.0, author: Google, Auto-updates enabled
Unlimited Elements for Elementor (Premium): version: 1.5.85, author: Unlimited Elements, Auto-updates disabled
UpdraftPlus - Backup/Restore: version: 1.23.16, author: UpdraftPlus.Com, DavidAnderson, Auto-updates enabled
WPCode Lite: version: 2.1.8, author: WPCode, Auto-updates enabled
wpDataTables - Tables & Table Charts: version: 3.4.2.4, author: TMS-Plugins, Auto-updates enabled
WP File Manager: version: 7.2.2, author: mndpsingh287, Auto-updates enabled
WP Reset: version: 1.98, author: WebFactory Ltd, Auto-updates enabled
WP Rocket: version: 3.15.4, author: WP Media, Auto-updates disabled
WPS Hide Login: version: 1.9.13.2, author: WPServeur, NicolasKulka, wpformation, Auto-updates enabled
WP Show Posts: version: 1.2.0-alpha.3, author: Tom Usborne, Auto-updates enabled
WP YouTube Lyte: version: 1.7.23, author: Frank Goossens (futtta), Auto-updates enabled

### wp-plugins-inactive (5) ###

Ele Custom Skin: version: 3.1.7, author: Dudaster.com, Auto-updates enabled
Happy Elementor Addons: version: 3.10.2, author: Leevio, Auto-updates enabled
Local Google Fonts: version: 0.22.0, author: EverPress, Auto-updates enabled
Perfmatters: version: 1.8.6, author: forgemedia, Auto-updates disabled
Wordfence Security: version: 7.11.3, author: Wordfence, Auto-updates enabled

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
imagick_version: Not available
file_uploads: 1
post_max_size: 128M
upload_max_filesize: 128M
max_effective_size: 128 MB
max_file_uploads: 20
gd_version: 2.3.3
gd_formats: GIF, JPEG, PNG, WebP, BMP, AVIF, XPM
ghostscript_version: 9.25

### wp-server ###

server_architecture: Linux 4.18.0-513.9.1.lve.el7h.x86_64 x86_64
httpd_software: LiteSpeed
php_version: 8.1.27 64bit
php_sapi: litespeed
max_input_variables: 10000
time_limit: 300
memory_limit: 768M
max_input_time: -1
upload_max_filesize: 128M
php_post_max_size: 128M
curl_version: 7.87.0 OpenSSL/1.1.1w
suhosin: false
imagick_availability: false
pretty_permalinks: true
htaccess_extra_rules: true
current: 2024-02-18T18:23:49+00:00
utc-time: Sunday, 18-Feb-24 18:23:49 UTC
server-time: 2024-02-19T02:23:48+08:00

### wp-database ###

extension: mysqli
server_version: 10.5.21-MariaDB-cll-lve
client_version: 10.5.23-MariaDB
max_allowed_packet: 536870912
max_connections: 1000

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/techspin/public_html/wp-content
WP_PLUGIN_DIR: /home/techspin/public_html/wp-content/plugins
WP_MEMORY_LIMIT: 512M
WP_MAX_MEMORY_LIMIT: 768M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_ENVIRONMENT_TYPE: Undefined
WP_DEVELOPMENT_MODE: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable
mu-plugins: writable

### google-site-kit ###

version: 1.120.0
php_version: 8.1.27
wp_version: 6.4.3
reference_url: https://www.techspinreview.com
amp_mode: no
site_status: connected-site
user_status: authenticated
verification_status: verified-non-site-kit
connected_user_count: 1
active_modules: site-verification, search-console, adsense, analytics, analytics-4, pagespeed-insights, tagmanager
recoverable_modules: none
required_scopes: 
	openid: ✅
	https://www.googleapis.com/auth/userinfo.profile: ✅
	https://www.googleapis.com/auth/userinfo.email: ✅
	https://www.googleapis.com/auth/siteverification: ✅
	https://www.googleapis.com/auth/webmasters: ✅
	https://www.googleapis.com/auth/adsense.readonly: ✅
	https://www.googleapis.com/auth/analytics.readonly: ✅
	https://www.googleapis.com/auth/tagmanager.readonly: ✅
capabilities: 
	googlesitekit_authenticate: ✅
	googlesitekit_setup: ✅
	googlesitekit_view_posts_insights: ✅
	googlesitekit_view_dashboard: ✅
	googlesitekit_manage_options: ✅
	googlesitekit_update_plugins: ✅
	googlesitekit_view_splash: ✅
	googlesitekit_view_authenticated_dashboard: ✅
	googlesitekit_view_wp_dashboard_widget: ✅
	googlesitekit_view_admin_bar_menu: ✅
	googlesitekit_view_shared_dashboard: ⭕
	googlesitekit_read_shared_module_data::["search-console"]: ⭕
	googlesitekit_read_shared_module_data::["adsense"]: ⭕
	googlesitekit_read_shared_module_data::["analytics"]: ⭕
	googlesitekit_read_shared_module_data::["analytics-4"]: ⭕
	googlesitekit_read_shared_module_data::["pagespeed-insights"]: ⭕
	googlesitekit_manage_module_sharing_options::["search-console"]: ✅
	googlesitekit_manage_module_sharing_options::["adsense"]: ⭕
	googlesitekit_manage_module_sharing_options::["analytics"]: ⭕
	googlesitekit_manage_module_sharing_options::["analytics-4"]: ⭕
	googlesitekit_manage_module_sharing_options::["pagespeed-insights"]: ✅
	googlesitekit_delegate_module_sharing_management::["search-console"]: ✅
	googlesitekit_delegate_module_sharing_management::["adsense"]: ⭕
	googlesitekit_delegate_module_sharing_management::["analytics"]: ⭕
	googlesitekit_delegate_module_sharing_management::["analytics-4"]: ⭕
	googlesitekit_delegate_module_sharing_management::["pagespeed-insights"]: ⭕
enabled_features: 
	adsModule: ⭕
	audienceSegmentation: ⭕
	gm3Components: ⭕
search-console_shared_roles: none
search-console_management: owner
adsense_shared_roles: none
adsense_management: owner
analytics_shared_roles: none
analytics_management: owner
analytics-4_shared_roles: none
analytics-4_management: owner
pagespeed-insights_shared_roles: none
pagespeed-insights_management: all_admins
search_console_property: https://www.techspinreview.com/
adsense_account_id: pub-893•••••••••••••
adsense_client_id: ca-pub-893•••••••••••••
adsense_account_status: approved
adsense_site_status: added
adsense_use_snippet: no
adsense_web_stories_adunit_id: none
adsense_setup_completed_timestamp: Not available
adsense_abr_use_snippet: no
adsense_abr_use_error_protection_snippet: no
adsense_abr_setup_status: undefined
analytics_account_id: 4258••••
analytics_property_id: UA-4258••••••
analytics_profile_id: 7468••••
analytics_use_snippet: yes
analytics_4_property_id: 3262554••
analytics_4_web_data_stream_id: 3884••••••
analytics_4_measurement_id: G-KJ••••••••
analytics_4_use_snippet: yes
analytics_4_available_custom_dimensions: none
tagmanager_account_id: 6002••••••
tagmanager_container_id: GTM-NN5••••
tagmanager_amp_container_id: none
tagmanager_use_snippet: no

`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by faisal-alvi** [comment]
@dvjrickkraft thank you for contacting us. It appears that the issue is connected to the active theme rather than the Simple Local Avatars plugin. However, upon inspecting your site on mobile, the avatar appears correctly.

![File](https://github.com/10up/simple-local-avatars/assets/25176325/d21ae533-b156-4f96-8bd5-978b9c9f56b7)

Upon reviewing the CSS, it appears as follows:

![image](https://github.com/10up/simple-local-avatars/assets/25176325/a360b616-af73-41b7-95f2-7f993ec2711a)

Previously, as per your comment^ above, this was set to `display: none`. It appears that recent changes made to your site may have resolved the issue. Could you please confirm if the problem has been resolved on your end?

**Comment by faisal-alvi** [comment]
Closing, please reopen if required.
