### ISSUE TITLE
Test against WP 5.3

### ISSUE THREAD

**Issue by jeffpaul** [10up/simple-local-avatars#35]
**Is your enhancement related to a problem? Please describe.**
Now that [WordPress 5.3 is released](https://wordpress.org/news/2019/11/kirk/), we'll want to test Simple Local Avatars to see if any incompatibility issues arise.

**Describe the solution you'd like**
- [ ] test Simple Local Avatars on WP 5.3
- [ ] open issues for any incompatibilities noted in testing
- [ ] resolve issues identified in testing
- [ ] bump "tested up to" version
- [ ] if code changes needed due to incompatibilities, ship a plugin release, otherwise use "Plugin asset/readme update" action to update "tested up to" version on .org repo

**Designs**
n/a

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by Waka867** [comment]
@jeffpaul I will go through this and do some testing asap

**Comment by jeffpaul** [comment]
Much appreciated @Waka867, thank you!

**Comment by Waka867** [comment]
@jeffpaul I've run through each feature on a WP5.3 install and everything looks good. I'm a bit newer so I just want to double check to make sure I understand a few things:

- Because of this situation where nothing needs to be, no version bump needs to happen
- I will need an SVN account in order to use the readme update action?

Thanks for the assistance. I just want to make sure I'm following protocol.

**Comment by jeffpaul** [comment]
@Waka867 if you're not seeing any issues after testing against WP 5.3, then feel free to submit a PR that updates that value in `readme.txt`.  I'll worry about updating the GitHub Action to ensure this propagates to WordPress.ORG correctly, thanks!

**Comment by Waka867** [comment]
@jeffpaul Request entered. If you are able to give a general explanation of how you ended up using the Github action that would be great!

https://github.com/10up/simple-local-avatars/pull/36

**Comment by jeffpaul** [comment]
@Waka867 I created #37 to update the formatting of our GitHub Actions to the current YML format.  You can read more about our actions here: https://10up.com/blog/2019/wordpress-github-actions-streamline-plugin-deployment/.

I'm waiting on a review for #37, once that's merged in I'll look to merge #36 so we can trigger the auto-deploy to .ORG for the "tested up to" value.

Thanks again for your help on this!

**Comment by Waka867** [comment]
@jeffpaul No problem

**Comment by jeffpaul** [comment]
Huh, I assumed #38 getting merged would trigger the GitHub Action and deploy the readme.txt change to .ORG.  Not seeing that in the [Actions tab](https://github.com/10up/simple-local-avatars/actions), will have to investigate what's going on there.

**Comment by dinhtungdu** [comment]
Currently, we don't have "new" GitHub actions configuration files on the `master` branch, so the asset doesn't get deployed. Adding actions config to the `master` branch will likely solve this issue. :)

**Comment by jeffpaul** [comment]
Closed by #38
