### ISSUE TITLE
Ability to programmatically set avatar

### ISSUE THREAD

**Issue by tripflex** [10up/simple-local-avatars#46]
Had a client contact me who is trying to set the avatar from this plugin, using a value from one of my plugins -- but it seems that the method to set the avatar is set to private:
https://github.com/10up/simple-local-avatars/blob/develop/simple-local-avatars.php#L329

And there doesn't really seem to be any other easy way to set this from a value outside of the plugin itself

**Comment by jeffpaul** [comment]
@tripflex welcome to Simple Local Avatars and thanks for the feedback!  If you're able I would love your help on this Issue, would be happy to review a PR for it, and will attempt to provide any assistance you might need.
