### ISSUE TITLE
Incompatibility with Elementor

### ISSUE THREAD

**Issue by jeffpaul** [10up/simple-local-avatars#49]
**Describe the bug**
[Previously reported on WordPress.org](https://wordpress.org/support/topic/it-doesnt-work-with-elementor-pro/#post-12911947):
> It doesn’t work with Elementor PRO?

**Steps to Reproduce**
First report:
> I tested the plugin on an author box built with Elementor, but the Gravatar is not shown.
It would be good to check why, due to the popularity of Elementor.

Second report:
> I’m facing the same issue with elementor pro. I’m trying to use Simple Local Avatars for my profile avatar then I tried to use it with the dynamic content available in elementor pro, but the profile picture doesn’t show up when I select the profile picture in the dynamic section. 

**Expected behavior**

**Screenshots**

**Environment information**
 - Device: 
 - OS: 
 - Browser and version: 
 - Simple Local Avatars version: 
 - Theme and version: 
 - Other installed plugin(s) and version(s): WordPress 5.4.1 and Elementor Pro 2.9.5

**Additional context**

**Comment by ghost** [comment]
Also having this issue and have some insights.

Elementor Pro Author Box uses the `get_avatar_url` function in author-box.php:717. It looks like the Simple Local Avatars plugin is only looking for `get_avatar`. 

That's where I've gotten with it and the fix likely lies in modifying `get_simple_local_avatar` to handle `get_avatar_url`.

Can @jeffpaul (Hi Jeff) take this home from here?

**Comment by dinhtungdu** [comment]
@johnsicili Can you please test #40 to see if it fixes this issue?

**Comment by ghost** [comment]
@dinhtungdu That fixed the issue! Thank you! 🙏
