### ISSUE TITLE
Implement `get_avatar_url` the same as `get_avatar`

### ISSUE THREAD

**Issue by ammon-lockwood** [10up/simple-local-avatars#57]
**Is your enhancement related to a problem? Please describe.**
Yes, currently you can get the avatar from simple local avatars by calling `get_avatar` and passing the appropriate arguments. We would like to be able to do the same thing with `get_avatar_url`. Specifically in our case the issue is that the WPGraphQL plugin uses the `get_avatar_url` to populate the `avatar` field when requesting user information. When this happens we only get back the default Gravatar icons and not the simple local avatar that we have created.

**Describe the solution you'd like**
We would like to be able to use the simple local avatars with our GraphQL and in order to do that we need to have `get_avatar_url` use simple local avatars as well

**Describe alternatives you've considered**
We could also override the `get_avatar_url` filter in our functions file of the theme. We'd prefer to not do that since that ties our theme very tightly to this plugin. It also feels more correct to have the plugin return the URL when calling `get_avatar_url`

**Additional context**
Additionally if `get_avatar_url` returns the url then the `get_avatar` function could call that to get the appropriate URL to add to the `src`

**Comment by jeffpaul** [comment]
@sumnercreations does https://github.com/10up/simple-local-avatars/pull/40 resolve this for you?

**Comment by ammon-lockwood** [comment]
@jeffpaul I'm looking at that PR and it does _sounds_ like what we need, however, when I checked out that branch and tried to query for the avatar any user that has a local avatar has `null` returned. Perhaps I should comment over there as well.

**Comment by dinhtungdu** [comment]
@sumnercreations After you check out that branch, do the local avatars display in the user list of the admin area?

Update: I tested the #40 again and both `get_avatar` and `get_avatar_url` are working on my end. Can you provide more information about your set up so we can debug your issue better?

**Comment by ammon-lockwood** [comment]
@dinhtungdu you're right I do get the correct URLs as well with the default functions. I've found the issue and I'll post on #40
