### ISSUE TITLE
Apply a proper maximum file size restriction

### ISSUE THREAD

**Issue by Shirkit** [10up/simple-local-avatars#58]
**Describe the solution you'd like**
I'd like to be able to set a maximum upload size (100kb for example) so that my users don't upload a 10mb image.

-------------------

### Underlying problem

This has been suggested and appears that there's some code to deal with it: https://github.com/10up/simple-local-avatars/blob/e058862b7b9633ebf416b894ffac4210efa7f60e/simple-local-avatars.php#L373

But it does not work, as it bypasses the Wordpress maximum filesize checking. Even defining on the global wordpress filter

```
add_filter( 'upload_size_limit', 'my_upload_size_limit', 10, 3);
function my_upload_size_limit($i1, $i2, $i3) {
	return 100;
}
```

This last block Limits the Media upload page, but it does not restricts the Simple Local Avatar way of upload, since it calls directly `media_handle_upload`, which does not check for file size.

-------------

### Proposed solution

A proper way to solve this would be similar to what you have here https://github.com/10up/simple-local-avatars/blob/e058862b7b9633ebf416b894ffac4210efa7f60e/simple-local-avatars.php#L362 but instead doing something like this
```
if ( $_FILES['simple-local-avatar']['size'] > DEFINED_SIZE_IN_BYTES ) ) {
	//throw error here;
	return;
}
```

Of course, you could just hook the previous filter to get the information. I can submit a PR, but this is a really simple check, just need proper error throwing.

**Comment by jeffpaul** [comment]
@Shirkit welcome to Simple Local Avatars and thanks for the well-thought-out feedback, its greatly appreciated!  A properly functioning filesize limit seems reasonable, though I've yet to double check the items you've asserted in your comment, but I'd welcome a PR to this affect and we can iterate on things there until its ready for merge.
