### ISSUE TITLE
Breaks wordpress functions: get_avatar and get_avatar_url

### ISSUE THREAD

**Issue by t-lock** [10up/simple-local-avatars#61]
Thanks for the great work on this plugin! 

However, I have encountered a fairly critical bug:

**Describe the bug**
The core wordpress function `get_avatar()` works nicely with simple-local-avatars, unless you need to use additional functionality like adding a class or another custom attribute. 

**Steps to Reproduce**
1. Use theme code: `<?= get_avatar(get_current_user_id(), 96, "", "", array('class' => "my-class", 'extra_attr' => 'data-id="1234"')) ?>` without simple-local-avatars activated.
2. Load the page, inspect front end, notice that the class and data-attr are present
3. Activate simple-local-avatars
4. Load the page, inspect front end, notice that the class and data-attr are **no longer present**

**Expected behavior**
All arguments/features from wordpress' core function `get_avatar` should work with simple-local-avatars. For the full list, see: https://developer.wordpress.org/reference/functions/get_avatar/

This bug prevents simple-local-avatars from being a no-code drop-in replacement for gravatar, on themes that use the full functionality of `get_avatar()`

**Comment by jeffpaul** [comment]
@t-lock we're working to finalize a release, including work on updating to current avatar filters (see #40).  If you want to test that branch or the current develop branch to let us know if that resolves your issues, that would be great.  You can otherwise wait for the next release and test that version.

**Comment by dinhtungdu** [comment]
With change introduced in #40, SLA doesn't override the `get_avatar` function anymore but uses the core function instead. So any extra attributes passed to the function will be output.

I tested the code above, and here is the output html when simple local avatar is activated, the `data-id` is present:
```
<img alt="" src="http://oss.test/wp-content/uploads/2020/10/avatar-96x96.jpg" srcset="http://oss.test/wp-content/uploads/2020/10/avatar-192x192.jpg 2x" class="avatar avatar-96 photo my-class" data-id="1234" loading="lazy" width="96" height="96">
```

**Comment by t-lock** [comment]
@jeffpaul awesome! thanks for the quick reply. I'd be happy to help with testing, but looks like @dinhtungdu has beat me to it. 

Closing this issue.

Thanks again for your work on this plugin!
