### ISSUE TITLE
Ability to set default avatar

### ISSUE THREAD

**Issue by jeffpaul** [10up/simple-local-avatars#78]
**Is your enhancement related to a problem? Please describe.**
Noting the following received via [10up.com](https://10up.com/plugins/simple-local-avatars-wordpress/comment-page-10/#comment-1126022):
> One feature i would love too see added / while not taking away from the light weight nature is…
An option to set the Default image used if someone has not yet uploaded an image.
>
> Currently it defaults to options from Gravatar but it would be really nice if we could set a custom default image :)

**Describe the solution you'd like**
We'll want to consider the following:
- [ ] is this sort of feature worthwhile in this otherwise simple, lightweight plugin?
- [ ] should this be a per-site option, enabled network-wide, or handled some other way?

**Designs**

**Describe alternatives you've considered**

**Additional context**

**Comment by dinhtungdu** [comment]
Here is my UI idea if we decide to implement this feature:

![image](https://user-images.githubusercontent.com/5423135/123649403-ea511680-d853-11eb-8de4-dc9bb30f8328.png)

**Comment by jeffpaul** [comment]
@dinhtungdu works for me!

**Comment by worldsdream** [comment]
This is the only feature that I need. Thank you.

**Comment by Mahyulan** [comment]
Yes, the solution would be great.
Only waiting to be implemented ;-)

**Comment by pixelbart** [comment]
Something like this would be cool. Then you don't have to upload an image, but create images with the users initials.

![image](https://user-images.githubusercontent.com/5339107/137358995-8bb514e1-35c3-4a48-9bf9-ba11a1220c2c.png)

Translation:

* Gravatar deaktivieren = Disable Gravatar
* Textfarbe = Text color
* Hintergrundfarbe = Background color
* Vorschau = Preview

**Comment by worldsdream** [comment]
I needed a replacement for  wp user avatar plugin. This feature was the only one that I was missing. 

It’s taking a lot of time to implement is so I found a great alternative for wp user avatar: 

https://wordpress.org/plugins/one-user-avatar/

**Comment by faisal-alvi** [comment]
@worldsdream FYI - this feature is now [released](https://wordpress.org/plugins/simple-local-avatars/) with 2.4.0.

**Comment by worldsdream** [comment]
@faisal-alvi

Glad to see that the feature is added. 
I am going to install the plugin and try the feature.
