### ISSUE TITLE
Allow import from WP User Avatar / ProfilePress

### ISSUE THREAD

**Issue by jeffpaul** [10up/simple-local-avatars#80]
**Is your enhancement related to a problem? Please describe.**
As seen on [WP.org](https://wordpress.org/support/topic/move-from-wp-user-avatar/#post-14657633), folks are migrating to Simple Local Avatars from WP User Avatar / ProfilePress and looking for help migrating in their users avatars.  

**Describe the solution you'd like**
Leverage [Gist](https://gist.github.com/philipjohn/822d3521a95481f6ad7e118a7106fbc7) to help script this migration (properly crediting the author of course).

**Designs**
Possibly include an “Import settings from…” option in settings to import settings from competing plugins starting with WP User Avatar.

**Describe alternatives you've considered**

**Additional context**

**Comment by claytoncollie** [comment]
Hi @jeffpaul  @helen Sent me this issue and said it would be a good one to get my feet wet with the OSS practice. Below is how I would tackle this issue. Please send me your direction and I'll work on this over the next week or so :)

- [ ] Write function from gist linked in main issue to migrate from Wp User Avatar
- [ ] Wrap script into wp-cli command `wp simple-loca-avatars migrate wp-user-avatar`
- [ ] Add button to `options-dicussion.php` to run script from wp-admin using either REST API or AJAX

The only part I do not agree with within the gist is to delete the Wp User Avatar value in the database. It should not be the responsibility of a plugin to remove another's data. A site owner might wish to go back to the original plugin and need the original data there. Also, if the script fails halfway through, having the original data present can aid in re-running the script from the start.

**Comment by jeffpaul** [comment]
@claytoncollie the other part to consider is functionality in multisite, as I got a report that the gist wasn't working on multisite so you'll want to check that as you get into crafting the function.  Otherwise your approach sounds good! 🚀
