### ISSUE TITLE
Upload image / photo, rest worpress api is possible?

### ISSUE THREAD

**Issue by andrerds** [10up/simple-local-avatars#86]
Hello, is it possible to send photos through wordpress rest api to a specific endpoint?
I see that in return when doing get to users/1
I have the return of simple_local_avatar as an object, but I don't know how to send the image.
I'm using Ionic/Angular on the front.
Can you guide me?

**Comment by dkotter** [comment]
@andrerds Thanks for the question! Yes, you can make a POST request to the default users endpoint and within that request, send a `simple_local_avatar` object with the image input data and it will get set as the avatar. See https://wordpress.org/support/topic/post-avatar-using-rest-api/#post-14061014 for more info

**Comment by andrerds** [comment]
> @andrerds Thanks for the question! Yes, you can make a POST request to the default users endpoint and within that request, send a `simple_local_avatar` object with the image input data and it will get set as the avatar. See https://wordpress.org/support/topic/post-avatar-using-rest-api/#post-14061014 for more info

Hey man, thanks a lot, I'll do the tests.
