### ISSUE TITLE
Add Settings link after activation and associated settings screenshot + copy

### ISSUE THREAD

**Issue by jeffpaul** [10up/simple-local-avatars#87]
**Is your enhancement related to a problem? Please describe.**
[Originally reported on WordPress.org](https://wordpress.org/support/topic/nice-work-but-needs-improvement/):
> Also most Plugins that have a settings page would have a settings link in the Plugins page underneath it’s name and this does not making it hard to find where the settings page is, but the author does explain this in their documentation.

**Describe the solution you'd like**
After installing SLA, there's no direction of where to find any admin settings.  Let's look to add a "Settings" link under the plugin name on the Installed Plugins page (e.g. wp-admin/plugins.php) that links to wp-admin/options-discussion.php to better help direct admins on where to customize their SLA experience.  Let's also add a screenshot of this setting with particular focus on the SLA settings and ensure the screenshot copy notes this is where the plugin settings reside.

**Designs**
n/a

**Describe alternatives you've considered**
keep as-is, possibly just adding a screenshot and copy to point out where the admin settings reside.

**Additional context**
Ensure that any PR and associated release that adds this to SLA credits @ggedde / https://profiles.wordpress.org/ggedde/ for the inspiration on this.

**Comment by rahulsprajapati** [comment]
@jeffpaul 

I've attached screenshot for plugin settings page for highlight + crop/focus here:

- [screenshot-2.png](https://user-images.githubusercontent.com/10358350/145263011-356c8d26-3750-4727-acb2-79ba1f5b3703.png)
