### ISSUE TITLE
Avatar rating text is not translated properly if a user has a custom language set

### ISSUE THREAD

**Issue by dkotter** [10up/simple-local-avatars#88]
**Describe the bug**
Reported [here](https://wordpress.org/support/topic/translation-of-ratings-doesnt-work-for-user-language/). The Avatar Rating text is translated properly if a site language is set but not if a user language is set.

Looking into it, I believe it's related to this: https://make.wordpress.org/core/2016/11/07/changed-loading-order-for-current-user-in-4-7/. Basically where we have those [strings set](https://github.com/10up/simple-local-avatars/blob/develop/includes/class-simple-local-avatars.php#L15) is loaded prior to the user object being initialized, so the user's set language is never available and thus won't be considered when translating.

There may be other approaches but it may be as simple as moving those text strings to the actual function that needs them, which should be late enough in the loading process to fix the problem. We do use the avatar ratings (G, PG, etc) in other places, so those need to stay but the actual text strings are only used in a single location.

**Steps to Reproduce**

1. Select a site language other than English (es_ES for instance). Ensure proper language packs get installed
2. Go to your profile page and note the Avatar Rating text is translated
3. Turn site language back to english
4. Set user language to a different language (es_ES again)
5. Note the Avatar Rating text is not translated

**Expected behavior**
All text should be translated if a different language is chosen and translations are available

**Comment by ActuallyConnor** [comment]
Hey @dkotter here's a simple PR I made to fix this issue [https://github.com/10up/simple-local-avatars/pull/89](https://github.com/10up/simple-local-avatars/pull/89)

Let me know if you have any questions 😄
