### ISSUE TITLE
Ask: when set avatar image - image not shows (media / upload)

### ISSUE THREAD

**Issue by brm-ryd** [10up/simple-local-avatars#93]
Hi,

Apologies, are there anything i can check when i use the simple-local-avatars when set the image avatar for the profile user it wont show for the image instead only white background like below image screenshot
![image](https://user-images.githubusercontent.com/9689138/147221072-93134ddc-72fc-4638-8d10-cd7b5c72e31c.png)

* When i used custom theme does it a must to use get_avatar function php in my theme to make it works ?
* Let say when i use this simple-local-avatars plugin when i uploaded image for avatar for specific profile it should be create a file image in Uploads folder isnt ? if not created - are there anything i can check (assumed i set directory of uploads for 750 & www-data user)

Again many thanks for your help & sorry for this question.

**Comment by faisal-alvi** [comment]
@brm-ryd Thank you for taking interest in the plugin and asking questions!

> 1. Apologies, are there anything i can check when i use the simple-local-avatars when set the image avatar for the profile user it wont show for the image instead only white background like below image screenshot

To exactly detect the issue and fix it, can you please provide/answer the following information/questions?

1. Can you please share the file you tried to upload?
2. On which WP version did the issue occurred?
3. And what version of the plugin?

> 2. When i used custom theme does it a must to use get_avatar function php in my theme to make it works ?

You can also use `get_avatar_url()` to get the avatar URL.

> 3. Let say when i use this simple-local-avatars plugin when i uploaded image for avatar for specific profile it should be create a file image in Uploads folder isnt ? if not created - are there anything i can check (assumed i set directory of uploads for 750 & www-data user)

Yes, it is uploaded as a WP media file so all no the avatars are stored in the uploads folder. 

_By the way, you can ask questions on the official Support Page [here](https://wordpress.org/support/plugin/simple-local-avatars/)._

**Comment by brm-ryd** [comment]
@faisal-alvi , 

- the file which i choose uploaded is some regular image which its uploaded correctly in the uploads directory & also i had tested by using existing file from media file as well (example as attached
![goldfish](https://user-images.githubusercontent.com/9689138/148317120-f468a828-30ca-47cd-92f2-3a43195185fe.jpg)
)
- Wordpress version 5.8.2
- Plugin version 2.2.0
- Php version 7.3 on latest though
- Is it something i need to add in functions.php on my themes directory for using the plugin to be able working correctly ?

Many thanks for the feedback!

**Comment by faisal-alvi** [comment]
Thank you for providing the details.

I have tried to upload your image in the same configuration you shared and the file was successfully uploaded without any issues.

![SLA-93-image-uploaded](https://user-images.githubusercontent.com/25176325/148355311-08e9eb9b-5639-47c7-8178-9bbfa35e8b00.png)
[image link](https://www.screencast.com/t/dBH6KYwwGY)

Can you please deactivate all the other plugins and try again?

**Comment by brm-ryd** [comment]
Sorry @faisal-alvi , i had been disable all plugins and then enable only the simple-local-avatar but still same like attached - only blank display image when i choose image for one of the user .
![image](https://user-images.githubusercontent.com/9689138/148484146-ec92f7be-e5a4-4b4c-9a06-1b511864c179.png)


Is there anything i should add in some themes functions.php for testing this event ?

**Comment by jeffpaul** [comment]
@brm-ryd what does that admin notification say at the top of the screen?  Are you seeing anything in the browser console that might tip off what's not allowing the uploaded avatar to display?

**Comment by brm-ryd** [comment]
Sorry @jeffpaul  uploaded image working as its really stored / created in uploads directory,  i dont see any notifications though after i choose the image (both from media existint / uploads new)

**Comment by jeffpaul** [comment]
@brm-ryd are you using something like Azure or other storage service to offload your media files?

**Comment by brm-ryd** [comment]
no @jeffpaul - only host the in the regular vps 1 instance for this wordpress site

**Comment by jeffpaul** [comment]
@brm-ryd what role is the user you're trying to set that image?

**Comment by brm-ryd** [comment]
@jeffpaul Currently i login with administrator role to set the image of user and the users i tried to set the image profile is regular & my admin account

**Comment by jeffpaul** [comment]
@brm-ryd is the avatar displayed on the frontend of your site properly?

**Comment by brm-ryd** [comment]
no @jeffpaul, as in frontend backend it just like blank (no standard gravatar default image as well) 
![image](https://user-images.githubusercontent.com/9689138/148486452-b5c04751-4389-43d3-a74e-3e80ecfd3070.png)

**Comment by faisal-alvi** [comment]
@brm-ryd If feasible, can you please create a dummy user for us to check into your site so we can investigate in detail?

**Comment by brm-ryd** [comment]
Sorry @faisal-alvi - i'll need to ask another person for this, does regular user should be okay / need an administrator role ?

**Comment by faisal-alvi** [comment]
@brm-ryd administrator role would be best as we would not face any capabilities issue while testing.

**Comment by jeffpaul** [comment]
@brm-ryd can you confirm your browser version, operating system version, theme version, and any other active plugin versions?  Our best guess is that there's a plugin conflict, but hard to triage without being able to properly replicate your environment... thanks!

**Comment by brm-ryd** [comment]
Sorry @faisal-alvi  & @jeffpaul , im not yet get the confirmation regarding access to the wp-admin for you, btw below are the details i can share to you - i only can think something related custom theme / plugin which like you said possible conflict
- my browser version (chrome Version 97.0.4692.99 (Official Build) (64-bit)), i believe browser not the issue as i had tested simple-local-avatars in another site its works fine
- Debian stretch 9 
- theme version, 
       jeo-theme	active	none	1.4.0 (custom theme)
       newspack-theme	parent	none	1.43.1
- plugin list aside of simple-local-avatars

    akismet	active	available	4.2.1
cloudflare	active	none	4.7.0
co-authors-plus	active	none	3.4.92
complianz-gdpr-premium	inactive	none	4.8.0
contact-form-7	active	available	5.5.3
edit-author-slug	active	none	1.8.3
jeowp	active	none	2.4.0
newspack-plugin	active	none	1.70.0
newspack-blocks	active	none	1.20.0
newspack-image-credits-1.0.1	active	none	1.0.1
newspack-media-partners	active	none	1.0.0
optimize-your-feed-for-feedly	active	none	1.0
redis-cache	active	available	2.0.22
safe-svg	active	none	1.9.9
google-site-kit	active	available	1.48.1
pubsubhubbub	active	none	3.1.1
wp-cron-control	inactive	none	0.7.1
wp-mail-smtp	active	none	3.2.1
flush-opcache	active	none	4.1.2
wps-hide-login	active	available	1.9.2
wordpress-seo	active	available	17.8
wpseo-news	active	none	13.1
wordpress-seo-premium	active	none	17.8

Again many thanks & sorry,

**Comment by faisal-alvi** [comment]
@brm-ryd thanks for sharing the details. I have again tested it in Safari, Chrome, and Firefox, it is working without any issues.

> i believe browser not the issue as i had tested simple-local-avatars in another site its works fine

As per your mentioned note, closing this ticket.
