### ISSUE TITLE
Test against WordPress 5.9

### ISSUE THREAD

**Issue by sudip-md** [10up/simple-local-avatars#95]
**Is your enhancement related to a problem? Please describe.**

**Describe the solution you'd like**

- [ ]  test WP New Relic on WordPress 5.9
- [ ] open issues for any incompatibilities noted in testing
- [ ] resolve issues identified in testing
- [ ]  bump "tested up to" version
- [ ] if code changes needed due to incompatibilities, ship a plugin release, otherwise use "Plugin asset/readme update" action to update "tested up to" version on .org repo

**Designs**
n/a

**Describe alternatives you've considered**
None

**Additional context**

**Comment by claytoncollie** [comment]
I've always wanted a workflow like this as a standard github action so that I could test an existing plugin against new versions of WP and if nothing is broken, release a new version or as this ticket says, use the `Plugin asset/readme update` action. I'll be follow this ticket to see how it goes.

**Comment by jeffpaul** [comment]
@claytoncollie we've started to roll out end-to-end tests using Cypress and using both the latest WP version and WP trunk (plus the minimum WP version stated by the plugin).  There's probably some additional GH Action work that could be done that further automates the issue/PR handling here when new major WP releases ship, but probably worth discussing that in a separate issue (perhaps in the readme/asset updater action repo) so we can get to an agreement on optimal approach.

**Comment by sudip-md** [comment]
I have tested this plugin in WordPress 5.9 version and it is working fine.

WP version : 5.9
Plugin version : 2.2.0
CC: @ankitguptaindia @jeffpaul

**Comment by ankitguptaindia** [comment]
@jeffpaul This Plugin is ready for a WP 5.9 Compatibility Version Bump update. Thank you!
